apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: test
  labels:
    cluster: docker-desktop
spec:
  replicas: 2
  selector:
    matchLabels:
      cluster: docker-desktop
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        cluster: docker-desktop
        pipecd.dev/variant: primary
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.32.0
        args:
          - server
        ports:
        - containerPort: 9085
