apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-sync-no-pipeline
  labels:
    app: simple-k8s-sync-no-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-k8s-sync-no-pipeline
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: simple-k8s-sync-no-pipeline
        pipecd.dev/variant: primary
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.50.0
        args:
          - server
        ports:
        - containerPort: 9085
